spring:
  application:
    name: eureka-server
  datasource:
    url: jdbc:mysql://mysql-db:3306/card_management_registry
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
  instance:
    hostname: localhost

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
