spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/card_management_db
    username: root
    password: Dhaval@3679
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  config:
    import: "configserver:http://localhost:8888"

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
