spring:
  datasource:
    url: jdbc:mysql://localhost:3306/card_management_dev_db
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.cardmanagement.user_service: DEBUG
