spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://prod-mysql:3306/card_management_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka/}

logging:
  level:
    com.cardmanagement.user_service: INFO
  file:
    name: /app/logs/user-service.log
